name: hexyl # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.7.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: A command-line hex viewer # 79 char long summary
description: |
  hexyl is a simple hex viewer for the terminal. It uses a colored output to distinguish different categories of bytes (NULL bytes, printable ASCII characters, ASCII whitespace characters, other ASCII characters and non-ASCII).

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  hexyl:
    command: bin/hexyl
    plugs:
      - home

parts:
  hexyl:
    plugin: rust
    source: .
